version: "3.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gnote
    ports:
      - "8080:8080"
    networks: 
      - gnote_net

  db:
    image: "postgres:12.5"
    restart: always
    environment:
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
    volumes:
      - ./docker/data/db:/var/lib/postgresql/data
      - ./docker/sql/create_tables.sql:/docker-entrypoint-initdb.d/create_tables.sql
    ports:
      - "5432:5432"
    networks: 
      - gnote_net

  adminer:
    image: "adminer:4.7.8"
    restart: always
    ports:
      - "8000:8080"
    networks: 
      - gnote_net

networks: 
  gnote_net:
